server:
  port: 9999
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kpkartik777@gmail.com
    password: ehigmhbxfuwlqizl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    
